<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Umesh2850" failures="1" tests="10" name="FreeCRMTest" time="121.413" errors="0" timestamp="2021-09-11T00:48:55 IST">
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="validateLoggedInUserNameTest" time="2.162"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="validateContactPageLinkTest" time="1.578"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="validateDealsPageLinkTest" time="2.239"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="validateCompaniesPageLinkTest" time="1.664"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="validateTaskPageLinkTest" time="1.304"/>
  <testcase classname="com.crm.qa.testcases.HomePageTest" name="validateCasesPageLinkTest" time="2.391"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="validateLoginBtnDisplayedTest" time="0.028"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="validateLoginBtnTest" time="0.042"/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [#1x`Free CRM customer relationship management software cloud] but found [#1 Free CRM customer relationship management software cloud]">
      <![CDATA[java.lang.AssertionError: expected [#1x`Free CRM customer relationship management software cloud] but found [#1 Free CRM customer relationship management software cloud]
at com.crm.qa.testcases.LoginPageTest.loginPageTitleTest(LoginPageTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="loginTest" time="4.871"/>
</testsuite> <!-- FreeCRMTest -->
